os: linux
language: node_js
node_js:
  - '10'
before_install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  target_branch: master
  cleanup: true
  local_dir: docs/.vuepress/dist
  repo: whu-luojian/luojian.github.io
  token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
