sudo: required
language: node_js
node_js:
  - '10'
before_install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  target-branch: master
  skip-cleanup: true
  local-dir: docs/.vuepress/dist
  repo: whu-luojian/luojian.github.io
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
